apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager-rel
  namespace: cert-manager
spec:
  interval: 5m 
  chart:
    spec:
      reconcileStrategy: ChartVersion
      version: v1.14.5
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
        namespace: cert-manager
  values:
    installCRDs: true